### ISSUE TITLE
v1.2.2 does not work on Paper 1.16.4

### ISSUE THREAD

**Issue by lunarys** [anhcraft/CraftKit#11]
I just updated my Paper Server from 1.16.3 to 1.16.4 and now CraftKit (and AdvancedKeep) is not working anymore. I'm using the docker image `itzg/minecraft-server:latest` (Java 1.8).

```
[22:19:35 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing CraftKit v1.2.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at dev.anhcraft.craftkit.utils.MaterialUtil.<clinit>(MaterialUtil.java:91) ~[?:?]
        at dev.anhcraft.craftkit.internal.CraftKit.loadMtInfo(CraftKit.java:56) ~[?:?]
        at dev.anhcraft.craftkit.internal.CraftKit.onLoad(CraftKit.java:81) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-392]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: No enum constant dev.anhcraft.craftkit.cb_common.NMSVersion.v1_16_R3
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_212]
        at dev.anhcraft.craftkit.cb_common.NMSVersion.valueOf(NMSVersion.java:10) ~[?:?]
        at dev.anhcraft.craftkit.cb_common.NMSVersion.<clinit>(NMSVersion.java:22) ~[?:?]
        ... 8 more
```

```
[22:19:43 ERROR]: Error occurred while enabling CraftKit v1.2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class dev.anhcraft.craftkit.cb_common.NMSVersion
        at dev.anhcraft.craftkit.cb_common.internal.backend.BackendManager.<clinit>(BackendManager.java:12) ~[?:?]
        at dev.anhcraft.craftkit.internal.listeners.ServerListener.<clinit>(ServerListener.java:16) ~[?:?]
        at dev.anhcraft.craftkit.internal.CraftKit.onEnable(CraftKit.java:95) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-392]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[22:19:43 INFO]: [CraftKit] Disabling CraftKit v1.2.2
[22:19:43 ERROR]: Error occurred while disabling CraftKit v1.2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class dev.anhcraft.craftkit.cb_common.internal.backend.BackendManager
        at dev.anhcraft.craftkit.internal.CraftKit.onDisable(CraftKit.java:122) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-392]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

```
[22:19:43 ERROR]: Error occurred while enabling AdvancedKeep v1.5.6 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/anhcraft/craftkit/helpers/TaskHelper
        at dev.anhcraft.advancedkeep.AdvancedKeep.onEnable(AdvancedKeep.java:220) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-392]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-392]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: dev.anhcraft.craftkit.helpers.TaskHelper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.4.jar:git-Paper-392]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-392]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        ... 11 more
[22:19:43 INFO]: [AdvancedKeep] Disabling AdvancedKeep v1.5.6
```

**Comment by anhcraft** [comment]
Thanks for reporting.
It is now fixed. (e0e2bd86170848f16701e23883b7c05c8851d74b)
