### ISSUE TITLE
Initialization error on Paper 1.16.4 using CraftKit 1.2.3

### ISSUE THREAD

**Issue by lunarys** [anhcraft/CraftKit#12]
After the fix for #11 version 1.2.3 still does not work with paper 1.16.4.

```
[20:04:29 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] Please connect first initializing CraftKit v1.2.3 (Is it up to date?)
java.lang.UnsupportedOperationException: Please connect first
        at dev.anhcraft.jvmkit.helpers.HTTPConnectionHelper.read(HTTPConnectionHelper.java:181) ~[?:?]
        at dev.anhcraft.jvmkit.utils.HttpUtil.fetch(HttpUtil.java:40) ~[?:?]
        at dev.anhcraft.jvmkit.utils.HttpUtil.fetch(HttpUtil.java:14) ~[?:?]
        at dev.anhcraft.craftkit.internal.CBLibProvider.downloadNMSLib(CBLibProvider.java:19) ~[?:?]
        at dev.anhcraft.craftkit.internal.CraftKit.handleNMSLib(CraftKit.java:130) ~[?:?]
        at dev.anhcraft.craftkit.internal.CraftKit.onLoad(CraftKit.java:85) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

```
[20:04:37 ERROR]: Error occurred while enabling CraftKit v1.2.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at dev.anhcraft.craftkit.internal.CraftKit.onEnable(CraftKit.java:95) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.UnsupportedOperationException
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
        at dev.anhcraft.craftkit.internal.listeners.ServerListener.<clinit>(ServerListener.java:16) ~[?:?]
        ... 11 more
[20:04:37 INFO]: [CraftKit] Disabling CraftKit v1.2.3
[20:04:37 ERROR]: Error occurred while disabling CraftKit v1.2.3 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
        at dev.anhcraft.craftkit.internal.CraftKit.onDisable(CraftKit.java:122) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

```
[20:04:38 ERROR]: Error occurred while enabling AdvancedKeep v1.5.6 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/anhcraft/craftkit/helpers/TaskHelper
        at dev.anhcraft.advancedkeep.AdvancedKeep.onEnable(AdvancedKeep.java:220) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: dev.anhcraft.craftkit.helpers.TaskHelper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        ... 11 more
```

**Comment by anhcraft** [comment]
Fixed (dc8f567b7809939dad41ae4fad089d97564b9ad0)
