### ISSUE TITLE
Could not pass event EntityShootBowEvent to CraftKit v1.0.5 (Spigot 1.14.4)

### ISSUE THREAD

**Issue by lunarys** [anhcraft/CraftKit#2]
The following error occurs when I am fighting a skeleton.
It does not break anything as far as I see, but is still an Exception.

Tested with Java version: openjdk 1.8.0_222 and openjdk 12.0.2

`[18:00:22] [Server thread/ERROR]: Could not pass event EntityShootBowEvent to CraftKit v1.0.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:469) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntitySkeletonAbstract.a(EntitySkeletonAbstract.java:160) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.PathfinderGoalBowShoot.e(SourceFile:128) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.e(SourceFile:55) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_222]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_222]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_222]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_222]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_222]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_222]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_222]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_222]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_222]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_222]
        at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:80) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:649) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2457) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:502) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntityMonster.movementTick(SourceFile:39) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntitySkeletonAbstract.movementTick(EntitySkeletonAbstract.java:85) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2293) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:273) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.EntityMonster.tick(SourceFile:51) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:568) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.World.a(World.java:745) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:344) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Pair
        at dev.anhcraft.craftkit.internal.listeners.EntityListener.shoot(EntityListener.java:29) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        ... 34 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Pair
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
        at dev.anhcraft.craftkit.internal.listeners.EntityListener.shoot(EntityListener.java:29) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        ... 34 more
`

**Comment by lunarys** [comment]
It looks like the class Pair in [EntityListener](https://github.com/anhcraft/CraftKit/blob/master/spigot/src/main/java/dev/anhcraft/craftkit/internal/listeners/EntityListener.java#L4) is not found.

`~[?:1.8.0_222] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9] ... 34 more Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Pair at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]`

**Comment by anhcraft** [comment]
tks for your report, will fix soon
